'''
Copyright    : yongzhao.derek@gmail.com
FilePath     : \\NintAi-The-AI-Powered-Bike-Fit-Studio\\src\\ai_report.py
Author       : Yongzhao Chen
Date         : 2026-03-05 21:58:22
LastEditTime : 2026-03-05 21:58:22
LastEditors  : Yongzhao Chen && yongzhao.derek@gmail.com
Version      : 1.0
Describe & Note: 
'''
import os
from datetime import datetime

def generate_diagnostic_prompt(stats, view):
    """Dispatch to a view-specific prompt generator. 视角参数 view 用于选择模板。"""
    if view == 'front':
        return generate_front_prompt(stats)
    elif view == 'back':
        return generate_back_prompt(stats)
    else:
        # 默认侧面视角
        return generate_side_prompt(stats)


def generate_side_prompt(stats):
    date_str = datetime.now().strftime('%Y-%m-%d %H:%M')
    prompt = f"""
# 🚴 NintAi 骑行生物力学诊断申请书
**日期**: {date_str}

## 1. 核心角度数据 (Core Angles)
| 指标 | 测量值 | 参考范围 (Road/Tri) | 状态 |
| :--- | :--- | :--- | :--- |
| **下死点膝盖角度 (Knee Ext)** | {stats.get('knee_ext_max', 0):.1f}° | 140° - 150° | {'需注意' if stats.get('knee_ext_max', 0) > 155 or stats.get('knee_ext_max', 0) < 135 else '良好'} |
| **上死点膝盖角度 (Knee Flex)** | {stats.get('knee_flex_min', 0):.1f}° | 70° - 110° | - |
| **上死点髋关节角度 (Hip Closed)** | {stats.get('hip_closed_min', 0):.1f}° | 45° - 55° | - |
| **躯干倾角 (Torso Angle)** | {stats.get('back_avg', 0):.1f}° | 40° - 50° | - |
| **脚踝角度均值 (Foot Angle)** | {stats.get('foot_angle_avg', 0):.1f}° | 0° - 20° | - |

## 2. 稳定性追踪 (Lateral Tracking)
* **膝盖相对于脚踝的水平偏移均值**: {stats.get('knee_lateral_avg', 0):.2f} 像素
* **偏移标准差 (稳定性指标)**: {stats.get('knee_lateral_std', 0):.2f} (数值越小代表轨迹越稳定)

## 3. 诊断请求 (Prompt to AI)
你现在是一名顶级的职业 Bike Fitter。请根据以上数据分析：
1. **座包高度**: 结合下死点角度，判断座包是否需要调整？
2. **膝盖内扣分析**: 重点关注横向偏移数据。如果偏移量较大或不稳定，是否暗示锁片位置 (Q-Factor) 或足弓支撑需要调整？
3. **痛点关联**: 我在骑行台训练后，右腿内侧（内侧广肌/泪滴肌）有撕裂感的刺痛，请结合数据给出针对性建议。

---
*Generated by NintAi Tools - Powered by Perseverance*
"""
    return prompt


def generate_front_prompt(stats):
    # 为正面视频生成的针对性 Prompt
    return f"""
# 🚴 NintAi 骑行生物力学诊断申请书 (正面视角)
**核心数据 (横向追踪)**:
* **右腿膝盖横向偏移均值**: {stats.get('right_valgus_avg', 0):.2f} px
* **右腿偏移标准差 (稳定性)**: {stats.get('right_valgus_std', 0):.2f} (重点关注)
* **左腿膝盖横向偏移均值**: {stats.get('left_valgus_avg', 0):.2f} px
* **左腿偏移标准差 (稳定性)**: {stats.get('left_valgus_std', 0):.2f}

**诊断请求**:
你现在是一名顶级的 Fitter。请根据以上数据分析我的**膝盖追踪 (Knee Tracking)** 问题。
* 重点比较左右腿的稳定性标准差。标准差越大，说明膝盖横向晃动越剧烈（很可能是内扣）。
* 如果某侧标准差很大，请结合我之前提到的内侧痛，给出关于锁片间距 (Q-Factor) 或鞋垫支撑的建议。
"""


def generate_back_prompt(stats):
    # 为背面视频生成的针对性 Prompt
    return f"""
# 🚴 NintAi 骑行生物力学诊断申请书 (背面视角)
**核心数据 (骨盆稳定性)**:
* **骨盆倾角均值**: {stats.get('pelvic_tilt_avg', 0):.2f} 度
* **骨盆摆动标准差**: {stats.get('pelvic_tilt_std', 0):.2f} (标准差越大，意味着坐包上屁股扭动越厉害)

**诊断请求**:
你现在是一名顶级的 Fitter。请分析我的**骨盆稳定性**问题。
* 如果标准差较大（例如 > 3度），这暗示什么？是坐垫太高迫使骨盆代偿性下掉？还是核心力量不足或由于曲柄过长导致的上死点挤压？
* 请给出针对性的调整建议。
"""